version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:14.0.0 
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=POSTGRES
      - DB_ADDR=postgres
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=password
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "yourStrong(!)Password"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment: 
      - ConnectionStrings__CheckUp=Server=mssql;Database=CheckUp;Trusted_Connection=False;User Id=sa;Password=yourStrong(!)Password;MultipleActiveResultSets=true
    ports:
      - "1400:1400"
    depends_on:
      - mssql
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4300:80"
    depends_on:
      - backend
