version: '3'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Vivek@105"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
  maturity-evaluation-backend:
    build: .
    ports:
      - "1400:1400"      